# Example: Validation-only workflow for PRs
# This lightweight workflow only validates metrics without compilation

name: Validate Metrics

on:
  pull_request:
    paths:
      - 'metrics/**'
      - 'templates/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate metrics
        uses: rdwburns/better-dbt-metrics@v2
        with:
          validate-only: true
          fail-on-warning: false  # Set to true for stricter validation
          comment-on-pr: true     # Adds validation report to PR